### PR TITLE
BI-2798: Migrate BI Connector C auth plugin signing from legacy notary to Garasign

### PR DESCRIPTION
**Pull request by EthanHardyMongo**
This PR migrates from Notary Service to Garasign.

### CODE REVIEW

**Review by pmeredit — APPROVED** [review]
We don't distribute this for macos, so lgtm.

**Review by nbagnard — APPROVED** [review]
LGTM!


QQ: Do we always override the unsigned artifacts with the signed ones?

**Comment by EthanHardyMongo** [comment]
> LGTM!
> 
> QQ: Do we always override the unsigned artifacts with the signed ones?

Yes. Garasign signs the files, but doesn't change the name like Notary does.

**Comment by EthanHardyMongo** [comment]
evergreen merge

**Pull request merged**
